#run_a Booking and Payment
require './booking_multi_secure.rb'
#require './booking_payment_validation_secure.rb'
#require './booking_payment_secure.rb'
require './booking_request_accept_secure.rb'
require './booking_request_proposal_secure.rb'
require './booking_request_reject_secure.rb'
require './booking_secure.rb'
#require './booking_request_payment_accept_secure.rb'
#require './booking_request_payment_proposal_secure.rb'
#require './booking_request_payment_reject_secure.rb'
require './booking_request_proposal_secure.rb'
require './booking_request_reject_secure.rb'
require './booking_secure.rb'
#require './payment_validation_secure.rb'
#require './payment_secure.rb'
